Had this error in my deploy log on render:error TS6133: 'isLoading' is declared but its value is never read.So i came here to fix it by just console logging it